---

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Deploy mongodb config
  template:
    src: "{{ role_path }}/templates/mongod.conf.j2"
    dest: "{{ mongo_host_config }}"
  notify: "{{ mongo_container_restart_id }}"
