---

- name: include app admin distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Include app admin distribution specific setup
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

...
