---

encryptions:
  openssl: 
    encrypt:
      executable: "openssl"
      args: 
        - "aes-256-cbc" 
        - "-k" 
        - "{{.Key}}" 
        - "-in" 
        - "{{.In}}" 
        - "-out"
        - "{{.Out}}" 
        - "-e"
    decrypt:
      executable: "openssl"
      args: 
        - "aes-256-cbc" 
        - "-k" 
        - "{{.Key}}" 
        - "-in" 
        - "{{.In}}" 
        - "-out"
        - "{{.Out}}" 
        - "-d"

  ansible-vault:
    encrypt:
      executable: "ansible-vault"
      args: 
        - "encrypt" 
        - "{{.In}}"
      env: 
        - name: "ANSIBLE_VAULT_PASSWORD_FILE"
          value: "{{.Key}}"
    decrypt:
      executable: "ansible-vault"
      args: 
        - "decrypt" 
        - "{{.In}}"
      env: 
        - name: "ANSIBLE_VAULT_PASSWORD_FILE"
          value: "{{.Key}}"

secretGroups:
  ansible-all:
    key: "ansible_pass"
    encryption: "ansible-vault"
    secrets:
      - encrypted: "group_vars/all.yml"
        decrypted: "group_vars/all.yml"
      - encrypted: "group_vars/dockerhub.yml"
        decrypted: "group_vars/dockerhub.yml" 
      - encrypted: "group_vars/himate-test.yml"
        decrypted: "group_vars/himate-test.yml"
      - encrypted: "roles/users/defaults/main.yml"
        decrypted: "roles/users/defaults/main.yml"

  aws:
    key: "`cat openssl_aws_pass`"
    encryption: "openssl"
    secrets:
      - encrypted: ".aws/credentials/deploy.sh.enc"
        decrypted: ".aws/credentials/deploy.sh" 

  users:
    key: "`cat openssl_sec1_pass`"
    encryption: "openssl"
    secrets:
      - encrypted: "roles/users/files/10001_kf/authorized_keys.enc"
        decrypted: "roles/users/files/10001_kf/authorized_keys"
      - encrypted: "roles/users/files/9500_an/authorized_keys.enc"
        decrypted: "roles/users/files/9500_an/authorized_keys"
      - encrypted: "roles/users/files/9501_de/authorized_keys.enc"
        decrypted: "roles/users/files/9501_de/authorized_keys"
      - encrypted: "roles/users/files/9502_hi/authorized_keys.enc"
        decrypted: "roles/users/files/9502_hi/authorized_keys"
      - encrypted: "roles/users/templates/sudoers.j2.enc"
        decrypted: "roles/users/templates/sudoers.j2" 
      - encrypted: "roles/users/templates/sudoers.group.j2.enc"
        decrypted: "roles/users/templates/sudoers.group.j2"
