---

- name: dockerhub distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: dockerhub distribution specific setup
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

...
