---

- name: nexus distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: nexus distribution specific setup
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

...
