---

- name: Add docker repository key
  apt_key:
    id: "{{ docker_repo_key }}"
    keyserver: "{{ docker_repo_key_server }}"

- name: Add docker repository to apt
  apt_repository:
    repo: "{{ docker_repo }}"

- name: Install docker
  apt:
    name: "{{ item }}"
  with_items: "{{ docker_packages }}"

- name: Install docker pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ docker_pip_packages }}"

...
